version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  # Specify build.commands, then none of the pre-defined build jobs will be executed
  commands:
    - python -m virtualenv $READTHEDOCS_VIRTUALENV_PATH
    - python -m pip install --no-deps --extra-index-url https://testpypi.python.org/pypi imas_data_dictionary
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - find $READTHEDOCS_VIRTUALENV_PATH -type d -name imas
    - cp -a $READTHEDOCS_VIRTUALENV_PATH/dd_*/share/doc/imas/* $READTHEDOCS_OUTPUT/html/
    - cp -av $READTHEDOCS_OUTPUT/html/html_documentation.html $READTHEDOCS_OUTPUT/html/index.html
