[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "packaging"]
build-backend = "setuptools.build_meta"

[project]
name = "lumache"
authors = [{name = "Graziella", email = "graziella@lumache"}]
dynamic = ["version", "description"]

